title: "SILVRNEBYX Lab"
description: "An interdisciplinary lab exploring cybersecurity, artificial intelligence, emerging technology, and technical research."
baseurl: "/silvrnebyxlab"
url: "https://glsanclem.github.io"
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-remote-theme
